### ISSUE TITLE
Modules are broken

### ISSUE THREAD

**Issue by AlexDaniel** [TiMBuS/Net--IRC#13]
It seems like all of the modules are broken. https://github.com/TiMBuS/Net--IRC/commit/f063741f9c3fa066adb9135f12e083d8b0d5f389 introduces ``is cmd``, which in turn breaks all existing code.

What was
```perl6
method command_tell ( $ev, $match ) {
```
should now be written as
```perl6
method tell ( $ev, $match ) is cmd {
```
This, however, is not necessarily the best move. I've tried fixing it, but method ``8ball`` starts with a digit (which is not a valid name). Also, ``Help.pm`` still relies on ``command_`` prefixes.

I don't really get it. This change was made more than a year ago, how come the code base is not adapted?

**Comment by TiMBuS** [comment]
Oh. I wasn't aware I had broken backwards compatibility when I merged this. Probably because it had been sitting on the backburner for over a year!

The example modules being broken is unfortunate and I guess I'll look into fixing that.

As for the change in syntax: I'm quite fond of using traits to declare command handlers -- In fact I'd consider rewriting core callbacks like 'said' and such to use traits instead of a naming convention if I had the motivation. I feel it provides a more flexible system for this 'declarative' style approach. A relevant example of this flexibility is that we could provide a way to attach a command name to any arbitrary method, for example something like `method eightball() is cmd(:name('8ball')) {...}` seems quite useful to me.

**Comment by TiMBuS** [comment]
I think(?) I have fixed everything with this latest commit. Help module is currently untested because.. Well, I didn't actually write it or use it ever. But 8ball certainly does work now.

I'll leave this open for a week or so, just to make sure everything is running right. If you have any bugs or features that you want to bring up, feel free to reply here :)

**Comment by AlexDaniel** [comment]
Yeah, it works now.
