### ISSUE TITLE
Can't use CommandHandler for custom modules

### ISSUE THREAD

**Issue by ShimmerFairy** [TiMBuS/Net--IRC#17]
Like the title says, for some reason I can't make CommandHandler work with a module of my own. Trying to write my own kind of 8-ball as an example, if I make my own `said` multimethod that will work (of course using `nextsame` to get to the CommandHandler anyway), but the CommandHandler's dispatcher doesn't. For now I'll have to workaround by essentially doing command handling manually.

It's also worth noting that using the supplied modules works as expected, so it really is just a problem with using CommandHandler myself.

Here's some example code:

    class Foobar does Net::IRC::CommandHandler {
        my @replies = "a", "b", "bar";

        multi method cueball($ev, $match) is cmd {
            $ev.msg("{$ev.who}: {@replies.pick}");
        }
    }

**Comment by TiMBuS** [comment]
Woah. Sorry, I didn't see this issue at all? The perl6 group gets a bit noisy I guess..

Anyway. If I had to guess, maybe it's the `multi` method? Can't see any other reason it wouldn't work. That's conjecture. I'll actually test and report back in a few mins.

**Comment by TiMBuS** [comment]
Confirmed, multi-methods don't get dispatched.
Seems valid to have two of the same command that disambiguate based on method signature.. I'll see how hard it is to add support for them :)

**Comment by TiMBuS** [comment]
Fixed in the latest commit, but it needs a tiny bit more work! 
Multi-method command handlers sharing the same command name won't be disambiguated atm. So I'll leave this open until I fully fix it.

**Comment by TiMBuS** [comment]
I believe this is the best I can do. Multiple commands of the same name are now allowed, and all of them will be called. It doesn't matter if it's a multi method or not.

Disambiguating based on multi candidates could work BUT it would require you to either declare a prototype and flag it as the command (strange), or I need to figure out the generated prototype from your declared commands, grep out the non-Command candidates on a dispatch, then only dispatch to the closest matching one.. Which is the exact opposite of what I'm currently doing...

Please reopen if what I've implemented does not suit your use case. Otherwise this is done.

Thanks!
